"""
train_qlora.py
==============
Fine-tunes Meta-Llama-3-8B-Instruct using QLoRA (Quantized Low-Rank Adaptation)
on the synthetic Socratic dialogue dataset generated by generate_mock_data.py.

Architecture:
  - Base model loaded in 4-bit NF4 quantisation via BitsAndBytesConfig.
  - LoRA adapters injected into attention projections (r=16, lora_alpha=32).
  - Full training loop managed by trl.SFTTrainer with gradient checkpointing.

Usage:
    python train_qlora.py [--output_dir <path>] [--num_epochs <int>]
"""

import argparse
import os
from pathlib import Path
from typing import Optional

import torch
from datasets import Dataset, load_dataset
from peft import LoraConfig, TaskType, get_peft_model, prepare_model_for_kbit_training
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
)
from trl import SFTConfig, SFTTrainer

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

BASE_MODEL_ID: str = "meta-llama/Meta-Llama-3-8B-Instruct"
DATA_PATH: str = str(Path(__file__).parent.parent / "data" / "socratic_dialogues.jsonl")
DEFAULT_OUTPUT_DIR: str = str(Path(__file__).parent.parent / "checkpoints" / "qlora_socratic")

MAX_SEQ_LENGTH: int = 2048
TRAIN_SPLIT_RATIO: float = 0.95


# ---------------------------------------------------------------------------
# BitsAndBytes 4-bit Quant Config
# ---------------------------------------------------------------------------

def build_bnb_config() -> BitsAndBytesConfig:
    """
    Returns a BitsAndBytesConfig for NF4 quantisation.

    Returns:
        BitsAndBytesConfig: Configured for 4-bit NF4 with double quantisation.
    """
    return BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",           
        bnb_4bit_compute_dtype=torch.bfloat16,  
        bnb_4bit_use_double_quant=True,       
    )


# ---------------------------------------------------------------------------
# LoRA Configuration
# ---------------------------------------------------------------------------

def build_lora_config() -> LoraConfig:
    """
    Returns a LoRA configuration targeting the attention projection layers.

    Returns:
        LoraConfig: Fully configured LoRA specification.
    """
    return LoraConfig(
        r=16,
        lora_alpha=32,
        lora_dropout=0.05,
        bias="none",
        task_type=TaskType.CAUSAL_LM,
        target_modules=[
            "q_proj",
            "k_proj",
            "v_proj",
            "o_proj",
            "gate_proj",
            "up_proj",
            "down_proj",
        ],
        inference_mode=False,
    )


# ---------------------------------------------------------------------------
# Training Arguments
# ---------------------------------------------------------------------------

def build_training_args(output_dir: str, num_epochs: int) -> SFTConfig:
    """
    Constructs the SFTConfig (extends TrainingArguments) for supervised fine-tuning.

    Key decisions:
      - per_device_train_batch_size=4 + gradient_accumulation_steps=4: Effective
        batch size of 16. On an A100 80GB with 4-bit quantisation, the 8B model
        occupies ~10GB, leaving ~70GB for activations and KV cache.
      - gradient_checkpointing=True: Trades compute for memory by recomputing
        activations during backward pass. Reduces activation memory by ~sqrt(L).
      - bf16=True: A100's TF32 and BF16 tensor cores deliver 312 TFLOPS vs
        77 TFLOPS in FP32.
      - learning_rate=2e-4: Standard for LoRA fine-tuning; lower than full
        fine-tuning because only adapters are updated.

    Args:
        output_dir: Directory to save checkpoints and final model.
        num_epochs: Number of full passes over the training dataset.

    Returns:
        SFTConfig: Fully configured training arguments.
    """
    return SFTConfig(
        output_dir=output_dir,
        num_train_epochs=num_epochs,
        per_device_train_batch_size=4,
        per_device_eval_batch_size=4,
        gradient_accumulation_steps=4,          # Effective batch size = 16
        gradient_checkpointing=True,           
        optim="paged_adamw_8bit",               
        learning_rate=2e-4,
        lr_scheduler_type="cosine",
        warmup_ratio=0.05,
        bf16=True,                             
        tf32=True,                             
        logging_steps=10,
        eval_strategy="epoch",
        save_strategy="epoch",
        save_total_limit=2,
        load_best_model_at_end=True,
        report_to="wandb",                      
        run_name="qlora_socratic_algorithms_v1",
        dataloader_num_workers=4,
        group_by_length=True,                  
        max_seq_length=MAX_SEQ_LENGTH,
        dataset_text_field="text",
        packing=False,                          
    )


# ---------------------------------------------------------------------------
# Model & Tokeniser Loading
# ---------------------------------------------------------------------------

def load_model_and_tokeniser(
    model_id: str,
    bnb_config: BitsAndBytesConfig,
) -> tuple[AutoModelForCausalLM, AutoTokenizer]:
    """
    Loads the base causal language model with 4-bit quantisation and its tokeniser.

    Args:
        model_id: HuggingFace Hub model identifier.
        bnb_config: BitsAndBytesConfig for quantised loading.

    Returns:
        Tuple of (model, tokeniser).
    """
    tokeniser = AutoTokenizer.from_pretrained(model_id, use_fast=True)
    tokeniser.pad_token = tokeniser.eos_token
    tokeniser.padding_side = "right"  

    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        quantization_config=bnb_config,
        device_map="auto",              
        attn_implementation="flash_attention_2", 
        torch_dtype=torch.bfloat16,
        trust_remote_code=True,
    )

    model = prepare_model_for_kbit_training(
        model,
        use_gradient_checkpointing=True,
    )

    return model, tokeniser


# ---------------------------------------------------------------------------
# Dataset Loading
# ---------------------------------------------------------------------------

def load_training_data(data_path: str) -> tuple[Dataset, Dataset]:
    """
    Loads the JSONL dataset and splits it into train/eval partitions.

    Args:
        data_path: Absolute or relative path to the JSONL file.

    Returns:
        Tuple of (train_dataset, eval_dataset).
    """
    dataset = load_dataset("json", data_files={"train": data_path}, split="train")
    split = dataset.train_test_split(test_size=1 - TRAIN_SPLIT_RATIO, seed=42)
    return split["train"], split["test"]


# ---------------------------------------------------------------------------
# Main Training Entrypoint
# ---------------------------------------------------------------------------

def train(output_dir: str, num_epochs: int) -> None:
    """
    Orchestrates the full QLoRA fine-tuning pipeline.

    Pipeline:
      1. Load 4-bit quantised base model.
      2. Inject LoRA adapters and print trainable parameter count.
      3. Load and split the synthetic dialogue dataset.
      4. Initialise SFTTrainer and begin training.
      5. Save LoRA adapters to output_dir.

    Args:
        output_dir: Directory for checkpoints and final adapter weights.
        num_epochs: Number of training epochs.
    """
    print(f"[train_qlora] Starting QLoRA training on {BASE_MODEL_ID}")
    print(f"[train_qlora] Data path: {DATA_PATH}")
    print(f"[train_qlora] Output dir: {output_dir}")

    bnb_config = build_bnb_config()
    model, tokeniser = load_model_and_tokeniser(BASE_MODEL_ID, bnb_config)

    lora_config = build_lora_config()
    model = get_peft_model(model, lora_config)

    trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    total_params = sum(p.numel() for p in model.parameters())
    print(
        f"[train_qlora] Trainable params: {trainable_params:,} "
        f"({100 * trainable_params / total_params:.2f}% of {total_params:,} total)"
    )

    if not Path(DATA_PATH).exists():
        raise FileNotFoundError(
            f"Dataset not found at {DATA_PATH}. "
            "Run generate_mock_data.py first."
        )
    train_dataset, eval_dataset = load_training_data(DATA_PATH)
    print(f"[train_qlora] Train: {len(train_dataset)} | Eval: {len(eval_dataset)}")

    training_args = build_training_args(output_dir, num_epochs)
    trainer = SFTTrainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        processing_class=tokeniser,
        peft_config=lora_config,
    )

    trainer.train()

    final_adapter_path = Path(output_dir) / "final_adapter"
    trainer.model.save_pretrained(str(final_adapter_path))
    tokeniser.save_pretrained(str(final_adapter_path))
    print(f"[train_qlora] LoRA adapters saved to {final_adapter_path}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description="QLoRA fine-tuning for Socratic AI tutor")
    parser.add_argument(
        "--output_dir",
        type=str,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory for saving checkpoints and adapter weights",
    )
    parser.add_argument(
        "--num_epochs",
        type=int,
        default=3,
        help="Number of training epochs (default: 3)",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    os.makedirs(args.output_dir, exist_ok=True)
    train(output_dir=args.output_dir, num_epochs=args.num_epochs)
